services:
  - type: web
    name: portfolio-api
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
